### ISSUE TITLE
Improvements Tracker

### ISSUE THREAD

**Issue by dbongartz** [dbongartz/hsm4c#2]
- [ ] Reduce dependency on root->_active.
      Depend on a "current" node passed into the sc_run() function.
- [ ] Make History States Optional (Should be able to make the states and transitions completely `static const`)
- [ ] Make Hierachy Optional (To safe space in case if it is not needed)
- [ ] Decide on transition table location (Bound on global or individual state)
      Maybe make compile time flag to switch. (Tradeoff speed/size)
      Global --> 1 pointer less per state, 1 pointer extra per transaction, needs to search the whole list each run.
      For Automatic transactions even twice.
      State --> 1 pointer extra per state, 1 pointer less per transaction. Minimal search time. (for linear search).
- [ ] Remove duplication in sc_run()
- [ ] Think of way to pass non static user data.
      CONTAINER_OF --> Can't put states into table, pay what you use
      (void *) on each event sent --> Necessary when events have data attached
      (void *) on state --> Pay on each state always
